"""The frontend server.

Serves the four screens as static files, and nothing else. It holds no business
logic, no workbook, and no credentials - it is a web server in front of a folder
of HTML, CSS and JavaScript, and it talks to the backend the same way any
browser would.

Keeping it separate means the two halves fail independently: restarting the API
does not drop the page a reviewer is looking at, and a frontend deploy cannot
disturb a workbook mid-write. It also means the frontend can be replaced - by
nginx, by a CDN, by a framework's own dev server - without the backend caring.

The one thing it needs to know is where the backend is, which it publishes to
the page as /config.js. That is generated at request time from the environment,
so pointing the frontend at a different API is a restart, not a rebuild.
"""

from __future__ import annotations

import argparse
import json
import os
from functools import partial
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

PUBLIC_DIR = Path(__file__).resolve().parent / "public"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 3000
DEFAULT_API = "http://127.0.0.1:8000"


class FrontendHandler(SimpleHTTPRequestHandler):
    """Static files, plus a generated /config.js carrying the API address."""

    def __init__(self, *args, api_url: str, **kwargs):
        self.api_url = api_url
        super().__init__(*args, directory=str(PUBLIC_DIR), **kwargs)

    def do_GET(self):  # noqa: N802 - name fixed by http.server
        if self.path.split("?")[0] == "/config.js":
            self._serve_config()
            return
        super().do_GET()

    def _serve_config(self) -> None:
        # Only the address. People sign in with their own accounts now, so the
        # page has a session token of its own and no shared secret needs to
        # reach the browser at all. The service key deliberately stays on the
        # server side: publishing it here would hand every visitor an
        # administrator credential.
        body = (
            "/* Generated by the frontend server at request time. */\n"
            f"window.GST_API_BASE = {json.dumps(self.api_url)};\n"
        ).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/javascript; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def end_headers(self):
        # These are working files that change as the app is developed; a cached
        # copy of app.js against a newer API is a confusing way to lose an hour.
        self.send_header("Cache-Control", "no-cache, must-revalidate")
        super().end_headers()

    def log_message(self, fmt, *args):
        # One tidy line per request instead of the default's stderr noise.
        print(f"  {self.address_string()} - {fmt % args}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the GST automation frontend.")
    parser.add_argument("--host", default=os.environ.get("GST_FRONTEND_HOST", DEFAULT_HOST))
    parser.add_argument("--port", type=int, default=int(os.environ.get("GST_FRONTEND_PORT", DEFAULT_PORT)))
    parser.add_argument(
        "--api",
        default=os.environ.get("GST_API_BASE", DEFAULT_API),
        help="Base URL of the backend API (default: %(default)s)",
    )
    args = parser.parse_args()

    if not PUBLIC_DIR.is_dir():
        raise SystemExit(f"Frontend files not found at {PUBLIC_DIR}")

    handler = partial(FrontendHandler, api_url=args.api.rstrip("/"))
    server = HTTPServer((args.host, args.port), handler)

    print(f"Frontend  http://{args.host}:{args.port}")
    print(f"Backend   {args.api}")
    print("Sign in with your own account; this server holds no credentials.")
    print("Ctrl+C to stop.\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nFrontend stopped.")
        server.server_close()


if __name__ == "__main__":
    main()
